### ISSUE TITLE
Not Launching after installing November 2019 Juno updates

### ISSUE THREAD

**Issue by shamim2018** [elementary-tweaks/elementary-tweaks#118] opened 2019-11-27 10:57 UTC
Not Launching after installing November 2019 Juno updates. After clicking Tweak icon the whole System Settings stops.

**Comment by ryonakano** [comment] 2019-11-27 11:27
Duplicate of #115

**Comment by whydinnn** [comment] 2019-11-30 21:49
Please fix this issue, I have tried any various ways, and still not working.

**Comment by ryonakano** [comment] 2019-12-01 00:49
@whydinnn It's already fixed in the code of elementary-tweaks, but the repository which provides PPA on Launchpad [can't be synced](https://code.launchpad.net/~philip.scott/elementary-tweaks/github/+index) with the one on GitHub (this repository) thus we still can't release a fix.

If you need a temporary fix, see https://github.com/elementary-tweaks/elementary-tweaks/issues/115#issuecomment-559683999.

**Comment by whydinnn** [comment] 2019-12-01 07:59
It works, thank you

**Comment by Philip-Scott** [comment] 2019-12-01 17:28
Alright, the build has been successful and the PPA was updated. People should be getting the updates throughout the day as the package goes to the mirrors :) Let me know if there are any other problems with the update

https://code.launchpad.net/~philip.scott/+archive/ubuntu/elementary-tweaks

**Closed by Philip-Scott** 2019-12-01 17:28 UTC
