### ISSUE TITLE
 GLib-GIO-ERROR **: 06:06:25.915 tweaks not working

### ISSUE THREAD

**Issue by jbmatias** [elementary-tweaks/elementary-tweaks#119] opened 2019-12-01 22:12 UTC
when I go to settings and click Tweaks, the window gets hidden and nothing happens further.

this is the actual error: (io.elementary.switchboard:9724): GLib-GIO-ERROR **: 06:06:25.915: Settings schema 'io.elementary.desktop.wingpanel.applications-menu' does not contain a key named 'rows'
Trace/breakpoint trap

http://i.imgur.com/qFPxREM.png

**Comment by ryonakano** [comment] 2019-12-01 23:59
Duplicate of #115

**Comment by ryonakano** [comment] 2019-12-02 00:04
This issue should be fixed in the latest update, try to check updates.

**Comment by jbmatias** [comment] 2019-12-02 00:30
@ryonakano sir how do I update it? I mean I already tried to reinstall it but its not working :( I am inexperienced with linux but I am learning a lot and doing well, only is that I am not sure what exactly to do to fixed it

**Comment by jbmatias** [comment] 2019-12-02 00:42
got it working now, I did remove the repository first and then reinstall again

**Comment by alissontenorio** [comment] 2019-12-02 03:34
do:
sudo apt update
sudo apt upgrade (or sudo apt dist-upgrade)

**Comment by ryonakano** [comment] 2019-12-03 08:14
@jbmatias Could you close this issue if it now works?

**Closed** 2019-12-03 08:26 UTC
