### ISSUE TITLE
Changing cursor theme doesn't work

### ISSUE THREAD

**Issue by uncertainquark** [elementary-tweaks/elementary-tweaks#46] opened 2017-05-16 06:23 UTC
Changing the cursor theme only works in non-elementary apps. The default cursor is shown when interacting with the elementary system + apps and the expected one is shown only when using a non-elementary app.

I am setting it to use breeze-cursor-theme, if that is relevant.

**Comment by Philip-Scott** [comment] 2017-06-05 12:51
Duplicate of #33

**Closed by Philip-Scott** 2017-06-05 12:51 UTC
Labels: status: duplicate
