### ISSUE TITLE
PPA broken? Cannot add

### ISSUE THREAD

**Issue by mr-bobz** [elementary-tweaks/elementary-tweaks#86] opened 2018-09-21 03:11 UTC
```
:~$ sudo add-apt-repository ppa:philip.scott/elementary-tweaks
Cannot add PPA: 'ppa:~philip.scott/ubuntu/elementary-tweaks'.
ERROR: '~philip.scott' user or team does not exist
```

**Comment by Philip-Scott** [comment] 2018-09-21 03:19
Well the PPA still exists so I'll have to investigate tomorrow 
morning :) here's the link to the repo https://launchpad.net/~philip.scott/+archive/ubuntu/elementary-tweaks

**Comment by mr-bobz** [comment] 2018-09-21 04:48
Appreciate the quick response. Did it have **archive** in the link before?

**Comment by Philip-Scott** [comment] 2018-09-21 21:36
Hmmm, no idea but i can't reproduce the problem. It's working for me on elementary OS Juno. What OS are you trying to install it to?


```
~ $ sudo add-apt-repository ppa:philip.scott/elementary-tweaks
[sudo] password for felipe:          
 system settings panel for elementary OS that lets you easily and safely customise your desktop's appearance  https://github.com/elementary-tweaks/elementary-tweaks
 More info: https://launchpad.net/~philip.scott/+archive/ubuntu/elementary-tweaks
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://repo.steampowered.com/steam precise InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                             
Get:3 http://packages.elementary.io/appcenter bionic InRelease [5,894 B]                                                 
Hit:4 http://packages.microsoft.com/repos/vscode stable InRelease                                                        
Hit:5 http://dl.google.com/linux/chrome/deb stable Release                                                               
Hit:6 https://deb.opera.com/opera-stable stable InRelease                                                                
Hit:7 https://download.docker.com/linux/ubuntu bionic InRelease                                                          
Hit:8 http://us.archive.ubuntu.com/ubuntu bionic InRelease                                                               
Hit:9 http://repository.spotify.com stable InRelease                                                                     
Hit:10 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                       
Hit:11 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic InRelease                                             
Hit:12 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                      
Get:13 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata [52.0 kB]                               
Hit:14 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                    
Hit:16 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease                                         
Get:18 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic InRelease [15.9 kB]                         
Hit:17 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease                                           
Get:19 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic/main i386 Packages [816 B]
Get:20 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic/main amd64 Packages [816 B]
Get:21 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic/main Translation-en [304 B]
Fetched 75.7 kB in 3s (30.1 kB/s)      
```

**Comment by Philip-Scott** [comment] 2018-09-26 00:15
Closing issue... Please re-open if you can still reproduce it :)

**Closed by Philip-Scott** 2018-09-26 00:15 UTC

**Comment by mr-bobz** [comment] 2018-09-26 01:59
I am using ` elementary OS 0.4.1 (Loki 64-bit)`.

Yes still have the issue. It waits for a while before running into error.. wonder some network timeout, I will investigate more, thanks.
